pkg install root-repo
pkg install unstable-repo
pkg install x11-repo
pkg install python2
pkg install git
pkg install ruby
pkg install lolcat
gem install lolcat
pkg install curl
pkg install pip
pip2 install requests
pip2 install mechanize
pkg install perl
pkg install openssh
pkg install metasploit
